#################################################
# Playbook to run nexpose scan-engine's container
#################################################
---

################################## linux ##############################

# Install Docker on remote hosts if it's not installed

- name: install docker on linux hosts
  hosts: linux
  become: true
  vars_files:
    - ./default.yaml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Update apt and install docker-ce-cli
      apt: update_cache=yes name=docker-ce-cli state=latest

    - name: Update apt and install containerd.io
      apt: update_cache=yes name=containerd.io state=latest

    - name: make sure that docker was started and enabled
      service:
              name: docker
              state: started
              enabled: yes

    - name: Install Docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      ignore_errors: yes


    - name: Install Docker Module for Python
      pip:
        name: docker

#    - name: Pull default Docker image
#      docker_image:
#        name: "{{ default_container_image }}"
#        source: pull

    # Creates the number of containers defined by the variable create_containers, using values from vars file
#    - name: Create default containers
#      docker_container:
#        name: "{{ default_container_name }}{{ item }}"
#        image: "{{ default_container_image }}"
#        command: "{{ default_container_command }}"
#        state: present
#      with_sequence: count={{ create_containers }}

# Pull the docker image & run the container


    - name: pull an image
      docker_image:
         name: med97ch/nexp-se
         source: pull


    - name: create the container
      docker_container:
         name: scane-engine
         image: med97ch/nexp-se
#         volumes:
         exposed_ports:
            - '40814'



################################## Windows #######################################

- name: install docker on windows hosts and pull the needed images
  hosts: windows

  tasks:
  - name: Check the minimum Windows build number
    include_tasks: check-build-number.yml
    tags: check

  - name: Install Windows Containers and Hyper-V Windows Features (if not already present)
    include_tasks: install-windows-container-features.yml
    tags: dockerinstall

  - name: Install Docker on Windows (always the newest version) and pull needed base images
    include_tasks: install-docker.yml
    tags: dockerinstall

  - name: Install Docker Compose (also always the newest version)
    include_tasks: install-docker-compose.yml
    tags: dockerinstall

  - name: Run a Microsoft Docker Windows Testcontainer
    include_tasks: run-test-container.yml

  - name: Run nexpose scan-engine container
    win_shell: "docker run --name nexpose-scanner med97ch/nexp-se"
